apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: the-project

resources:
  - manifests/namespace.yaml
  - manifests/database-configmap.yaml
  - manifests/configmap.yaml
  - manifests/postgres-statefulset.yaml
  - manifests/postgres-service.yaml
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/ingress.yaml

commonLabels:
  app: the-project
  version: v1

namespace: project 