apiVersion: v1
kind: Service
metadata:
  name: pingpong-service
  namespace: exercises
spec:
  selector:
    app: pingpong
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP 