apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-cronjob
  namespace: project
spec:
  schedule: "0 * * * *"  # Every hour at minute 0
  concurrencyPolicy: Forbid  # Don't run if previous job is still running
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: todo-cronjob
            image: todo-cronjob:latest
            imagePullPolicy: Never
            env:
            - name: TODO_API_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-cronjob-config
                  key: TODO_API_URL