apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-project
  labels:
    app: the-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: the-project
  template:
    metadata:
      labels:
        app: the-project
    spec:
      containers:
      - name: the-project
        image: the-project:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        volumeMounts:
        - name: image-cache
          mountPath: /data
      volumes:
      - name: image-cache
        persistentVolumeClaim:
          claimName: shared-pvc
