apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-project
  namespace: project
  labels:
    app: the-project
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: the-project
  template:
    metadata:
      labels:
        app: the-project
    spec:
      containers:
      - name: the-project
        image: gcr.io/influential-rex-464619-p8/the-project:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: IMAGE_PATH
          valueFrom:
            configMapKeyRef:
              name: the-project-config
              key: IMAGE_PATH
        - name: TIMESTAMP_PATH
          valueFrom:
            configMapKeyRef:
              name: the-project-config
              key: TIMESTAMP_PATH
        - name: CACHE_DURATION
          valueFrom:
            configMapKeyRef:
              name: the-project-config
              key: CACHE_DURATION
        - name: IMAGE_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: the-project-config
              key: IMAGE_SERVICE_URL
        - name: BACKEND_TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: the-project-config
              key: BACKEND_TIMEOUT
        - name: IMAGE_TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: the-project-config
              key: IMAGE_TIMEOUT
        - name: MAX_TODO_LENGTH
          valueFrom:
            configMapKeyRef:
              name: the-project-config
              key: MAX_TODO_LENGTH
        - name: TODO_BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: the-project-config
              key: TODO_BACKEND_URL