apiVersion: v1
kind: Service
metadata:
  name: the-project-service
  namespace: project
spec:
  type: ClusterIP
  selector:
    app: the-project
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080 
      