apiVersion: v1
kind: Service
metadata:
  name: todo-backend
  namespace: project
spec:
  type: ClusterIP
  selector:
    app: todo-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080 