name: Delete Environment

on:
  delete:
    branches: [ master, main, develop, feature/*, hotfix/* ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b

jobs:
  delete-environment:
    name: Delete Environment
    runs-on: ubuntu-latest

    steps:
      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2

      - name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: 'Get GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          project_id: '${{ env.PROJECT_ID }}'
          location: '${{ env.GKE_ZONE }}'

      - name: 'Determine namespace'
        run: |
          BRANCH="${{ github.ref_name }}"
          if [[ "$BRANCH" == "master" || "$BRANCH" == "main" ]]; then
            echo "NAMESPACE=project" >> $GITHUB_ENV
          else
            NAMESPACE=$(echo "$BRANCH" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g' | sed 's/-\+/-/g' | sed 's/^-\|-$//g')
            echo "NAMESPACE=$NAMESPACE" >> $GITHUB_ENV
          fi

      - name: 'Delete namespace'
        run: |
          if kubectl get namespace $NAMESPACE; then
            kubectl delete namespace $NAMESPACE
            echo "Deleted namespace: $NAMESPACE"
          else
            echo "Namespace $NAMESPACE does not exist, nothing to delete"
          fi 